# Generated by Django 3.0.2 on 2020-03-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modify_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dsecription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
